item {
    id: 1
    name: 'tongyip'
}
item {
    id: 2
    name: 'foitong'
}
item {
    id: 3
    name: 'tongyod'
}
item {
    id: 4
    name: 'kanomchan'
}
item {
    id: 5
    name: 'kanompiakpoon'
}
item {
    id: 6
    name: 'kanomtom'
}
item {
    id: 7
    name: 'O-eo'
}
item {
    id: 8
    name: 'kanomkai'
}